version: "2"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.0.1
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webserver-net
  nginx-proxy-acme:
    image: nginxproxy/acme-companion:2.2.1
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=prjoh.dev@gmail.com
    networks:
      - webserver-net
  app:
    container_name: node-server
    build: .
    environment:
      - VIRTUAL_HOST=prjoh.xyz
      - LETSENCRYPT_HOST=prjoh.xyz
    depends_on:
      - nginx-proxy
    networks:
      - webserver-net

networks:
  webserver-net:
    driver: "bridge"
volumes:
  acme:

